from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("lnbot")
except PackageNotFoundError:
    __version__ = "0.0.0"

from .client import AsyncLnBot, LnBot
from .errors import (
    BadRequestError,
    ConflictError,
    ForbiddenError,
    LnBotError,
    NotFoundError,
    UnauthorizedError,
)
from .types import (
    AddressInvoiceResponse,
    AddressResponse,
    BackupPasskeyBeginResponse,
    CreateWalletResponse,
    CreateWebhookResponse,
    InvoiceEvent,
    InvoiceResponse,
    InvoiceStatus,
    L402ChallengeResponse,
    L402PayResponse,
    L402PaymentStatus,
    PaymentEvent,
    PaymentResponse,
    PaymentStatus,
    VerifyL402Response,
    WalletEvent,
    WalletEventType,
    RecoveryBackupResponse,
    RecoveryRestoreResponse,
    RestorePasskeyBeginResponse,
    RestorePasskeyCompleteResponse,
    RotateApiKeyResponse,
    TransactionResponse,
    TransactionType,
    TransferAddressResponse,
    WalletResponse,
    WebhookResponse,
)

__all__ = [
    "__version__",
    "LnBot",
    "AsyncLnBot",
    "LnBotError",
    "BadRequestError",
    "UnauthorizedError",
    "ForbiddenError",
    "NotFoundError",
    "ConflictError",
    "WalletResponse",
    "CreateWalletResponse",
    "RotateApiKeyResponse",
    "InvoiceResponse",
    "InvoiceStatus",
    "InvoiceEvent",
    "AddressInvoiceResponse",
    "PaymentResponse",
    "PaymentStatus",
    "PaymentEvent",
    "WalletEvent",
    "WalletEventType",
    "AddressResponse",
    "TransferAddressResponse",
    "TransactionResponse",
    "TransactionType",
    "CreateWebhookResponse",
    "WebhookResponse",
    "RecoveryBackupResponse",
    "RecoveryRestoreResponse",
    "BackupPasskeyBeginResponse",
    "RestorePasskeyBeginResponse",
    "RestorePasskeyCompleteResponse",
    "L402ChallengeResponse",
    "VerifyL402Response",
    "L402PayResponse",
    "L402PaymentStatus",
]
